spring:
  application:
    name: api-gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8080

zuul:
  routes:
    user-service:
      serviceId: user
      path: /v1/user-service/**