server:
  port: 9001

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/tmall?useSSL=false&characterEncoding=utf8
    password: xxc6711758
    username: root
  hikari:
        maximum-pool-size: ${UBT_GW_SQL_POOL_SIZE:30}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/