server:
  port: 8030

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/tmall?useSSL=false&characterEncoding=utf8
    password: xxc6711758
    username: root
  hikari:
    maximum-pool-size: 30
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#安全配置
  security:
  #oauth2配置
    oauth2:
      resource:
        filter-order: 3
